# Generated by Django 4.0.2 on 2022-02-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avgRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='totalReviews',
            field=models.IntegerField(default=0),
        ),
    ]
